<div class="row">
    <div class="col-md-offset-2 col-md-8">

        <div class="portlet box blue-dark">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-bars"></i> 選單 </div>
                <div class="tools">
                </div>
            </div>
            <div class="portlet-body">
                <?php foreach($list as $item => $file) { ?>
                    <div class="panel-group accordion scrollable">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#<?php echo $item; ?>" aria-expanded="false">
                                        <?php echo $item; ?>
                                    </a>
                                </h4>
                            </div>
                            <div id="<?php echo $item; ?>" class="panel-collapse collapse" aria-expanded="false">
                                <div class="panel-body">
                                    <?php foreach($file as $filename) { ?>
                                        <a href="/note/<?php echo $item; ?>-<?php echo $filename; ?>" class="btn default dark-stripe" style="margin: 2px;">
                                            <?php echo $filename; ?>
                                        </a>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        </div>

    </div>
</div>


