<div class="profile-content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXPERIENCE LINE -->
            <div class="portlet light portlet-fit ">
                <div class="portlet-body">
                    <div class="mt-timeline-2">
                        <div class="mt-timeline-line border-grey-steel"></div>
                        <ul class="mt-container">
                            <!-- JOB -->
                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-blue bg-font-blue border-grey-steel">
                                    <i class="icon-book-open"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">RD & SA</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">AAMS Co.,Ltd.</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2017 / 11 - 至今</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <h5>-建置FCM web notification</h5>
                                            <h5>-產品核心</h5>
                                            <h5>-產品架構</h5>
                                            <h5>-社群討論區規劃、建置</h5>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- JOB -->
                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-green bg-font-green border-grey-steel">
                                    <i class="icon-paper-plane"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">SA & RD & Leader</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">禾多移動多媒體股份有限公司</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2016 / 10 - 2017 / 10</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <h5>-sw設計參與</h5>
                                            <h5>-處理大量推播發送程式（10000則/秒</h5>
                                            <h5>-導入php laravel架構重構後台系統</h5>
                                            <h5>-node.js socket線上客服系統規劃、建置</h5>
                                            <h5>-機器學習ANN研發</h5>
                                            <h5>-safari推播系統規劃、建置</h5>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- JOB -->
                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">SA</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2016 / 1 - 2016 / 10</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <h5>-系統分析師</h5>
                                            <h5>-需求訪談</h5>
                                            <h5>-專案可行性評估</h5>
                                            <h5>-設計新系統及服務</h5>
                                            <h5>-線上資料庫資料控管</h5>
                                            <h5>-專案進度控管、監督</h5>
                                            <h5>-系統錯誤追蹤窗口</h5>
                                            <h5>-API測試</h5>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- JOB -->
                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">QA Leader</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2015 / 1 - 2016 / 1</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <h5>-建置自動化測試環境</h5>
                                            <h5>-定義測試腳本架構</h5>
                                            <h5>-撰寫Test Case及測試腳本</h5>
                                            <h5>-統整測試報告</h5>
                                            <h5>-分配測試人員能量</h5>
                                            <h5>-自動測試教育訓練</h5>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- JOB -->
                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">QA</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2013 / 10 - 2015 / 1</div>
                                        </div>
                                        <div class="mt-content border-grey-steel">
                                            <h5>-撰寫Test Case</h5>
                                            <h5>-確認系統功能正確性</h5>
                                            <h5>-統整測試報告</h5>
                                            <h5>-Mantis、Redmine等專案管理軟體管理Bug</h5>
                                            <h5>-Bug追蹤</h5>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <!-- JOB -->
                        </ul>
                    </div>
                </div>
            </div>
            <!-- END EXPERIENCE LINE -->
        </div>
    </div>
</div>