<div class="profile-content">
    <div class="row">
        <div class="col-md-12">

            <div class="portlet light ">
                <div class="portlet-body">
                    <div class="row">

                        <div class="col-md-6">
                            <p class="font-blue-hoki">
                                <i class="fa fa-birthday-cake"></i>
                                1989 / 12 / 23
                            </p>
                            <p class="font-blue-hoki">
                                <i class="fa fa-graduation-cap"></i>
                                中國科技大學 (畢業)
                            </p>
                            <p class="font-blue-hoki">
                                <i class="fa fa-briefcase"></i>
                                程式設計師 (RD)
                            </p>
                            <p class="font-blue-hoki">
                                <i class="fa fa-briefcase"></i>
                                系統分析師 (SA)
                            </p>
                            <p class="font-blue-hoki">
                                <i class="fa fa-phone-square"></i>
                                0963-411-161
                            </p>
                            <p class="font-blue-hoki">
                                <i class="fa fa-envelope"></i>
                                jason945119@gmail.com
                            </p>
                        </div>

                        <div class="col-md-6">
                            <div class="well font-blue">
                                <strong>座右銘</strong><br><br>
                                <br>推倒重來不可取
                                <br>完美主義不可取
                                <br>權衡的基礎上妥協
                                <br>妥協的基礎上創新
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>
