<div class="profile-content">
    <div class="row">
        <div class="col-md-12">

            <div class="portlet light portlet-fit ">
                <div class="portlet-body">
                    <div class="mt-timeline-2">
                        <div class="mt-timeline-line border-grey-steel"></div>
                        <ul class="mt-container">

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-home"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">QA Leader</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2015 / 1 - 2016 / 1</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <p>-建置自動化測試環境</p>
                                            <p>-定義測試腳本架構</p>
                                            <p>-撰寫Test Case及測試腳本</p>
                                            <p>-統整測試報告</p>
                                            <p>-分配測試人員能量</p>
                                            <p>-自動測試教育訓練</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-blue bg-font-blue border-grey-steel">
                                    <i class="icon-plane"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">QA 測試</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2013 / 10 - 2015 / 1</div>
                                        </div>
                                        <div class="mt-content border-grey-steel">
                                            <p>-撰寫Test Case</p>
                                            <p>-確認系統功能正確性</p>
                                            <p>-統整測試報告</p>
                                            <p>-Mantis、Redmine等專案管理軟體管理Bug</p>
                                            <p>-Bug追蹤</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>