<div class="profile-content">
    <div class="row">
        <div class="col-md-12">

            <div class="portlet light portlet-fit ">
                <div class="portlet-body">
                    <div class="mt-timeline-2">
                        <div class="mt-timeline-line border-grey-steel"></div>
                        <ul class="mt-container">

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-blue bg-font-blue border-grey-steel">
                                    <i class="icon-book-open"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">RD & SA</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">AAMS Co.,Ltd.</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2017 / 11 - 至今</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <p>-建置FCM web notification</p>
                                            <p>-產品核心</p>
                                            <p>-產品架構</p>
                                            <p>-社群討論區規劃、建置</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-green bg-font-green border-grey-steel">
                                    <i class="icon-paper-plane"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">SA & RD & Leader</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">禾多移動多媒體股份有限公司</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2016 / 10 - 2017 / 10</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <p>-sw設計參與</p>
                                            <p>-處理大量推播發送程式（10000則/秒</p>
                                            <p>-導入php laravel架構重構後台系統</p>
                                            <p>-node.js socket線上客服系統規劃、建置</p>
                                            <p>-機器學習ANN研發</p>
                                            <p>-safari推播系統規劃、建置</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">SA</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2016 / 1 - 2016 / 10</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <p>-系統分析師</p>
                                            <p>-需求訪談</p>
                                            <p>-專案可行性評估</p>
                                            <p>-設計新系統及服務</p>
                                            <p>-線上資料庫資料控管</p>
                                            <p>-專案進度控管、監督</p>
                                            <p>-系統錯誤追蹤窗口</p>
                                            <p>-API測試</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">QA Leader</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2015 / 1 - 2016 / 1</div>
                                        </div>
                                        <div class="mt-content border-grey-salt">
                                            <p>-建置自動化測試環境</p>
                                            <p>-定義測試腳本架構</p>
                                            <p>-撰寫Test Case及測試腳本</p>
                                            <p>-統整測試報告</p>
                                            <p>-分配測試人員能量</p>
                                            <p>-自動測試教育訓練</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                            <li class="mt-item">
                                <div class="mt-timeline-icon bg-red bg-font-red border-grey-steel">
                                    <i class="icon-basket"></i>
                                </div>
                                <div class="mt-timeline-content">
                                    <div class="mt-content-container bg-white border-grey-steel">
                                        <div class="mt-title">
                                            <h3 class="mt-content-title">QA</h3>
                                        </div>
                                        <div class="mt-author">
                                            <div class="mt-author-name">
                                                <a href="javascript:;" class="font-blue-madison">新加坡商優達斯</a>
                                            </div>
                                            <div class="mt-author-notes font-grey-mint">2013 / 10 - 2015 / 1</div>
                                        </div>
                                        <div class="mt-content border-grey-steel">
                                            <p>-撰寫Test Case</p>
                                            <p>-確認系統功能正確性</p>
                                            <p>-統整測試報告</p>
                                            <p>-Mantis、Redmine等專案管理軟體管理Bug</p>
                                            <p>-Bug追蹤</p>
                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>