<div class="clearfix">
    <!-- BEGIN BURGER TRIGGER -->
    <div class="burger-trigger">
        <button class="menu-trigger">
            <img src="/assets/img/m_toggler.png" alt=""> </button>
        <div class="menu-overlay menu-overlay-bg-transparent">
            <div class="menu-overlay-content">
                <ul class="menu-overlay-nav text-uppercase">
                    <li>
                        <a href="/profile/education">個人簡歷</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="menu-bg-overlay">
            <button class="menu-close">&times;</button>
        </div>
        <!-- the overlay element -->
    </div>
    <!-- END NAV TRIGGER -->

    <!-- BEGIN LOGO -->
    <div class="page-logo">
        <h2>
            <?php echo \htmlspecialchars($title);?>
        </h2>
    </div>
    <!-- END LOGO -->

    <!-- BEGIN TOP NAVIGATION MENU -->
    <div class="top-menu">
        <ul class="nav navbar-nav pull-right">
            <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <i class="icon-envelope-open"></i>
                </a>
            </li>
            <!-- END INBOX DROPDOWN -->

            <!-- BEGIN USER LOGIN DROPDOWN -->
            <!-- END USER LOGIN DROPDOWN -->

        </ul>
    </div>
    <!-- END TOP NAVIGATION MENU -->

</div>