<div class="row">
    <div class="col-sm-12">
        <div class="note note-info">
            <p>點擊左上角 <code><i class="fa fa-bars"></i></code> 可開啟選單 </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-3">

        <div class="widget-blog text-center margin-bottom-20 clearfix" style="height: 442px; padding-top: 120px; background-image: url(/assets/img/natural.jpg);">
            <div class="widget-blog-heading text-uppercase">
                <h3 class="widget-blog-title" style="color:floralwhite">展示網站</h3>
                <span class="widget-blog-subtitle" style="color:floralwhite">持續施工中</span>
            </div>
            <div style="color:floralwhite">
                <p>我不是在寫CODE</p>
                <p>就是在抓BUG</p>
                <br>
            </div>
        </div>
    </div>

    <div class="col-sm-3">
        <div class="widget-blog text-center margin-bottom-20 clearfix" style="height: 442px; padding-top: 120px; background-image: url(/assets/img/earth.jpg);">
            <div class="widget-blog-heading text-uppercase">
                <h3 class="widget-blog-title" style="color:floralwhite">個人簡歷</h3>
                <span class="widget-blog-subtitle">here</span>
            </div>
            <div style="color:darkgrey">
                <p>將前往簡歷頁面 僅展示  "York"  個人相關資料</p>
                <br>
            </div>
            <a class="btn btn-danger text-uppercase" href="profile/information">前往</a>
        </div>
    </div>

    <div class="col-sm-6">
                <!-- BEGIN WIDGET TAB -->
        <div class="widget-bg-color-white widget-tab" style="height: 442px;">
            <div class="note note-info">
                <p>點擊 <code>前往</code> 前往至筆記頁面 </p>
            </div>
            <ul class="nav nav-tabs">
                <?php foreach($md_list as $item => $file) { ?>
                    <li class="<?php if($item == 'php'){ echo 'active';}; ?>">
                        <a href="#<?php echo $item;?>" data-toggle="tab"
                           <?php if($item == 'php'){ echo 'aria-expanded="true"';}else{ echo 'aria-expanded="false"';};?>>
                            <?php echo $item;?>
                        </a>
                    </li>
                <?php } ?>
            </ul>
            <div class="slimScrollDiv" ">
                <div class="tab-content scroller">
                    <?php foreach($md_list as $item => $file) { ?>
                        <div class="tab-pane fade <?php if($item == 'php'){ echo 'active in';}; ?>" id="<?php echo $item;?>">
                            <?php foreach($file as $filename) { ?>
                                <div class="widget-news margin-bottom-20">
                                    <img class="widget-news-left-elem" src="../assets/layouts/layout7/img/03.jpg" alt="">
                                    <div class="widget-news-right-body">
                                        <h3 class="widget-news-right-body-title">
                                            <?php echo $filename; ?>
                                            <a class="label label-default"href="/note/<?php echo $item; ?>-<?php echo $filename; ?>">
                                                前往
                                            </a>
                                        </h3>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <!-- END WIDGET TAB -->
    </div>
</div>

