<div class="row">
    <div class="col-md-12">

        <div class="portlet box blue-sharp">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>選單</div>
                <div class="tools">
                    <a href="javascript:;" class="expand" data-original-title="" title=""> </a>
                </div>
            </div>
            <div class="portlet-body">

                <div class="panel-group accordion scrollable">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#collapse_2_1" aria-expanded="false">
                                    php
                                </a>
                            </h4>
                        </div>
                        <div id="collapse_2_1" class="panel-collapse collapse" aria-expanded="false">
                            <div class="panel-body">
                                <a href="/note/php-echo物件class的方法.md" class="btn default dark-stripe">echo物件class的方法</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>


