<div class="profile-content">
    <div class="row">
        <div class="col-md-12">

            <div class="portlet light ">
                <div class="portlet-body">
                    <h4 class="block">frontend</h4>
                    <ul class="list-group">
                        <li class="list-group-item">
                            Html
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-half-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            javascript
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-half-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            jquery
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            bootstrap
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            css
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            Other few plugin
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>

                    </ul>
                    <h4 class="block">backend</h4>
                    <ul class="list-group">
                        <li class="list-group-item">
                            PHP
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            Mysql & Mariadb
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            Laravel
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            CI
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-half-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            Node.js
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            Python
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>

                    </ul>
                    <h4 class="block">basic</h4>
                    <ul class="list-group">
                        <li class="list-group-item">
                            Docker
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-half-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            LAMP LNMP
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-half-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            GCP
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-half-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            System Analyst
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            Machine Learning
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star-o" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>
                        <li class="list-group-item">
                            web Ｎotification
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                            <i class="fa fa-star" style="float: right;"></i>
                        </li>

                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
