<div class="profile-content">
    <div class="row">
        <div class="col-md-12">

            <div class="portlet light ">
                <div class="portlet-body font-blue-hoki">
                    <h3 class="block"><i class="fa fa-television"> frontend</i></h3>
                    <ul class="list-group">
                        <li class="list-group-item skill-star" data-id="3.5">Html</li>
                        <li class="list-group-item skill-star" data-id="3.5">javascript</li>
                        <li class="list-group-item skill-star" data-id="5">jquery</li>
                        <li class="list-group-item skill-star" data-id="4">bootstrap</li>
                        <li class="list-group-item skill-star" data-id="4">css</li>
                        <li class="list-group-item skill-star" data-id="4">Other few plugin</li>
                    </ul>
                    <h3 class="block"><i class="fa fa-server"> backend</i></h3>
                    <ul class="list-group">
                        <li class="list-group-item skill-star" data-id="5">PHP</li>
                        <li class="list-group-item skill-star" data-id="4">Mysql & Mariadb</li>
                        <li class="list-group-item skill-star" data-id="4">Redis</li>
                        <li class="list-group-item skill-star" data-id="4">Laravel</li>
                        <li class="list-group-item skill-star" data-id="3.5">CI</li>
                        <li class="list-group-item skill-star" data-id="3">Node.js</li>
                        <li class="list-group-item skill-star" data-id="3">Python</li>

                    </ul>
                    <h3 class="block"><i class="fa fa-wrench"></i> basic</h3>
                    <ul class="list-group">
                        <li class="list-group-item skill-star" data-id="3.5">Docker</li>
                        <li class="list-group-item skill-star" data-id="4">LAMP LNMP</li>
                        <li class="list-group-item skill-star" data-id="3.5">GCP</li>
                        <li class="list-group-item skill-star" data-id="3.5">System Analyst</li>
                        <li class="list-group-item skill-star" data-id="3">Machine Learning</li>
                        <li class="list-group-item skill-star" data-id="5">web Ｎotification</li>

                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
